### ISSUE TITLE
博主加油

### ISSUE THREAD

**Issue by jiajunhuang** [leonewang/LeoneAuberge#1]
加油，加油，哈哈哈。坐等博主分享js学习经验

**Comment by leonewang** [comment]
怎么知道我在更新

**Comment by jiajunhuang** [comment]
:clap: 顺手点进了博主的博客，顺手就跳到了github

**Comment by leonewang** [comment]
感觉 WordPress 太重了，打开慢，编写也慢，还是回 GitHub Pages

**Comment by jiajunhuang** [comment]
嗯~Github Pages在国内其实也不快， 有空分享分享呗~ 各种啊，css, js啥的，让我等开开眼界~~

ps: 我已经变成纯文本记录了 [http://blog.jiajunhuang.com]()

**Comment by leonewang** [comment]
还真是纯文本

**Comment by jiajunhuang** [comment]
观察了一段时间，除了投稿以后流量会大点，其他时候都小的可怜。所以博客需要的评论功能也显得没那么有必要。再加上markdown标准太多，于是换到reStructuredText了 :smile: 虽然github的markdown支持比较广泛

**Comment by leonewang** [comment]
自从开了马克飞象会员就没更新了，自动保存到印象笔记简直不要太好用


在2016年01月01日 17:41，jiajunhuang 写道:

观察了一段时间，除了投稿以后流量会大点，其他时候都小的可怜。所以博客需要的评论功能也显得没那么有必要。再加上markdown标准太多，于是换到reStructuredText了 虽然github的markdown支持比较广泛

**Comment by jiajunhuang** [comment]
这个嘛，个人看法是，一般保存到印象笔记里就不会看了。还是自己梳理一遍自己写成笔记靠谱点。
